export default {
  elements: [
    { abbr: "H", name: "html", href: "/html/introduccion/estructura-documento-html/" },
    { abbr: "Hd", name: "head", href: "/html/introduccion/estructura-documento-html/#la-etiqueta-head-metadatos" },
    { abbr: "Bd", name: "body", href: "/html/introduccion/estructura-documento-html/#la-etiqueta-body-cuerpo" },
    { abbr: "Ti", name: "title", href: "/html/cabecera/que-son-etiquetas-cabecera/#la-etiqueta-title" },
    { abbr: "Bs", name: "base", href: "/html/cabecera/que-son-etiquetas-cabecera/#la-etiqueta-base" },
    { abbr: "Lk", name: "link", href: "/html/cabecera/etiqueta-html-link/" },
    { abbr: "Mt", name: "meta", href: "/html/cabecera/etiqueta-html-meta/" },
    { abbr: "St", name: "style", href: "/html/cabecera/que-son-etiquetas-cabecera/" },
    {
      abbr: "P",
      name: "p",
      href: "/html/agrupacion/que-son/#párrafo-de-texto-etiqueta-p",
    },
    {
      abbr: "Hr",
      name: "hr",
      href: "/html/agrupacion/que-son/#separaci%C3%B3n-tem%C3%A1tica-etiqueta-hr",
    },
    {
      abbr: "Pre",
      name: "pre",
      href: "/html/agrupacion/etiqueta-html-pre/",
    },
    {
      abbr: "Bq",
      name: "blockquote",
      href: "/html/agrupacion/etiqueta-html-blockquote/",
    },
    {
      abbr: "Ol",
      name: "ol",
      href: "/html/agrupacion/etiquetas-html-ul-ol/",
    },
    {
      abbr: "Ul",
      name: "ul",
      href: "/html/agrupacion/etiquetas-html-ul-ol/",
    },
    {
      abbr: "Li",
      name: "li",
      href: "/html/agrupacion/etiquetas-html-ul-ol/",
    },
    {
      abbr: "Dl",
      name: "dl",
      href: "/html/agrupacion/etiqueta-html-dl/",
    },
    {
      abbr: "Dt",
      name: "dt",
      href: "/html/agrupacion/etiqueta-html-dl/",
    },
    {
      abbr: "Dd",
      name: "dd",
      href: "/html/agrupacion/etiqueta-html-dl/",
    },
    {
      abbr: "Fi",
      name: "figure",
      href: "/html/agrupacion/etiqueta-html-figure/",
    },
    {
      abbr: "Fc",
      name: "figcaption",
      href: "/html/agrupacion/etiqueta-html-figure/",
    },
    {
      abbr: "Dv",
      name: "div",
      href: "/html/agrupacion/etiqueta-html-div/",
    },
    {
      abbr: "Mn",
      name: "main",
      href: "/html/semantica/etiqueta-html-section-main-aside/",
    },
    { abbr: "A", name: "a", href: "/html/texto/etiqueta-html-a/" },
    {
      abbr: "Em",
      name: "em",
      href: "/html/texto/etiqueta-html-em/",
    },
    {
      abbr: "Str",
      name: "strong",
      href: "/html/texto/etiqueta-html-strong/",
    },
    {
      abbr: "Sm",
      name: "small",
      href: "/html/texto/etiqueta-html-small/",
    },
    {
      abbr: "S",
      name: "s",
      href: "/html/texto/etiqueta-html-s/",
    },
    {
      abbr: "Ci",
      name: "cite",
      href: "/html/texto/etiqueta-html-q-cite/",
    },
    {
      abbr: "Q",
      name: "q",
      href: "/html/texto/etiqueta-html-q-cite/",
    },
    {
      abbr: "Dfn",
      name: "dfn",
      href: "/html/texto/etiqueta-html-abbr-dfn/",
    },
    {
      abbr: "Ab",
      name: "abbr",
      href: "/html/texto/etiqueta-html-abbr-dfn/",
    },
    {
      abbr: "Da",
      name: "data",
      href: "/html/texto/etiqueta-html-time/",
    },
    {
      abbr: "Tim",
      name: "time",
      href: "/html/texto/etiqueta-html-time/",
    },
    {
      abbr: "Co",
      name: "code",
      href: "/html/texto/etiqueta-html-code/",
    },
    {
      abbr: "Va",
      name: "var",
      href: "/html/texto/etiqueta-html-time/#la-etiqueta-var",
    },
    {
      abbr: "Sa",
      name: "samp",
      href: "/html/texto/etiqueta-html-kbd-samp/",
    },
    {
      abbr: "Kb",
      name: "kbd",
      href: "/html/texto/etiqueta-html-kbd-samp/",
    },
    {
      abbr: "Sub",
      name: "sub",
      href: "/html/texto/etiqueta-html-sup-sub/",
    },
    {
      abbr: "Sup",
      name: "sup",
      href: "/html/texto/etiqueta-html-sup-sub/",
    },
    {
      abbr: "I",
      name: "i",
      href: "/html/texto/etiqueta-html-em/",
    },
    {
      abbr: "B",
      name: "b",
      href: "/html/texto/etiqueta-html-strong/",
    },
    {
      abbr: "U",
      name: "u",
      href: "/html/texto/etiqueta-html-mark/#la-etiqueta-u",
    },
    {
      abbr: "Mk",
      name: "mark",
      href: "/html/texto/etiqueta-html-mark/",
    },
    {
      abbr: "Sp",
      name: "span",
      href: "/html/texto/etiqueta-html-span/",
    },
    {
      abbr: "Br",
      name: "br",
      href: "/html/texto/etiqueta-html-br-wbr/",
    },
    {
      abbr: "Wbr",
      name: "wbr",
      href: "/html/texto/etiqueta-html-br-wbr/#la-etiqueta-wbr",
    },
    { abbr: "Img", name: "img", href: "/html/multimedia/etiqueta-html-img/" },
    { abbr: "Pic", name: "picture", href: "/html/multimedia/etiqueta-html-picture/" },
    {
      abbr: "Ifr",
      name: "iframe",
      href: "/html/multimedia/etiqueta-html-iframe/",
    },
    {
      abbr: "Emb",
      name: "embed",
      href: "/html/multimedia/etiqueta-html-iframe/",
    },
    {
      abbr: "Obj",
      name: "object",
      href: "/html/multimedia/etiqueta-html-iframe/",
    },
    {
      abbr: "Par",
      name: "param",
      href: "/html/multimedia/etiqueta-html-iframe/",
    },
    { abbr: "Vi", name: "video", href: "/html/multimedia/etiqueta-html-video/" },
    { abbr: "Au", name: "audio", href: "/html/multimedia/etiqueta-html-audio/" },
    { abbr: "Src", name: "source", href: "/html/multimedia/etiqueta-html-video/" },
    { abbr: "Trk", name: "track", href: "/html/multimedia/etiqueta-html-track/" },
    { abbr: "Map", name: "map", href: "#" },
    { abbr: "Ar", name: "area", href: "#" },
    { abbr: "Tb", name: "table", href: "/html/tablas/etiqueta-html-table/" },
    { abbr: "Cap", name: "caption", href: "/html/tablas/organizacion-tablas/" },
    { abbr: "Cg", name: "colgroup", href: "/html/tablas/columnas-en-tablas/" },
    { abbr: "Col", name: "col", href: "/html/tablas/columnas-en-tablas/" },
    { abbr: "TBd", name: "tbody", href: "/html/tablas/organizacion-tablas/" },
    { abbr: "THd", name: "thead", href: "/html/tablas/organizacion-tablas/" },
    { abbr: "TFt", name: "tfoot", href: "/html/tablas/organizacion-tablas/" },
    { abbr: "Tr", name: "tr", href: "/html/tablas/etiqueta-html-table/" },
    { abbr: "Th", name: "th", href: "/html/tablas/etiqueta-html-table/" },
    { abbr: "Td", name: "td", href: "/html/tablas/etiqueta-html-table/" },
    { abbr: "Frm", name: "form", href: "/html/formularios/etiqueta-html-form/" },
    { abbr: "Lab", name: "label", href: "/html/formularios/organizacion-de-campos/" },
    { abbr: "In", name: "input", href: "/html/formularios/etiqueta-html-input/" },
    { abbr: "But", name: "button", href: "/html/formularios/etiqueta-html-input-submit/" },
    { abbr: "Sel", name: "select", href: "/html/formularios/etiqueta-html-select/" },
    { abbr: "Dtl", name: "datalist", href: "/html/formularios/etiqueta-html-datalist/" },
    { abbr: "Og", name: "optgroup", href: "/html/formularios/etiqueta-html-select/" },
    { abbr: "O", name: "option", href: "/html/formularios/etiqueta-html-select/" },
    {
      abbr: "Ta",
      name: "textarea",
      href: "/html/formularios/etiqueta-html-textarea/",
    },
    { abbr: "Out", name: "output", href: "/html/formularios/etiqueta-html-input-numeros/" },
    {
      abbr: "Prg",
      name: "progress",
      href: "/html/formularios/etiqueta-html-progress/",
    },
    { abbr: "Met", name: "meter", href: "/html/formularios/etiqueta-html-meter/" },
    { abbr: "Fs", name: "fieldset", href: "/html/formularios/organizacion-de-campos/" },
    { abbr: "Le", name: "legend", href: "/html/formularios/organizacion-de-campos/" },
    { abbr: "Sc", name: "script", href: "/html/scripting/etiqueta-html-script/" },
    {
      abbr: "NSc",
      name: "noscript",
      href: "/html/scripting/etiqueta-html-script/#la-etiqueta-noscript",
    },
    {
      abbr: "Tp",
      name: "template",
      href: "https://lenguajejs.com/webcomponents/componentes/plantillas-html-webcomponents/#html-mediante-templates",
    },
    { abbr: "Sl", name: "slot", href: "https://lenguajejs.com/webcomponents/shadow-dom/slots/" },
    { abbr: "Cv", name: "canvas", href: "#" },
    { abbr: "Det", name: "details", href: "/html/scripting/etiqueta-html-details/" },
    { abbr: "Sum", name: "summary", href: "/html/scripting/etiqueta-html-details/#la-etiqueta-summary" },
    { abbr: "Dia", name: "dialog", href: "/html/scripting/etiqueta-html-dialog/" },
  ],
  semantics: [
    { abbr: "Art", name: "article", href: "/html/semantica/etiqueta-html-article/" },
    { abbr: "Sec", name: "section", href: "/html/semantica/etiqueta-html-section-main-aside/" },
    { abbr: "Nav", name: "nav", href: "/html/semantica/etiqueta-html-nav/" },
    { abbr: "Hg", name: "hgroup", href: "/html/semantica/etiqueta-html-h1/" },
    { abbr: "h1", name: "h1", href: "/html/semantica/etiqueta-html-h1/" },
    { abbr: "h2", name: "h2", href: "/html/semantica/etiqueta-html-h1/" },
    { abbr: "h3", name: "h3", href: "/html/semantica/etiqueta-html-h1/" },
    { abbr: "h4", name: "h4", href: "/html/semantica/etiqueta-html-h1/" },
    { abbr: "h5", name: "h5", href: "/html/semantica/etiqueta-html-h1/" },
    { abbr: "h6", name: "h6", href: "/html/semantica/etiqueta-html-h1/" },
    { abbr: "Sr", name: "search", href: "/html/semantica/etiqueta-html-search/" },
    { abbr: "Hdr", name: "header", href: "/html/semantica/etiqueta-html-header-footer/" },
    { abbr: "Ftr", name: "footer", href: "/html/semantica/etiqueta-html-header-footer/" },
    { abbr: "Asd", name: "aside", href: "/html/semantica/etiqueta-html-section-main-aside/" },
    { abbr: "Add", name: "address", href: "/html/semantica/etiqueta-html-address/" },
    { abbr: "Rub", name: "ruby", href: "#" },
    { abbr: "Rb", name: "rb", href: "#" },
    { abbr: "Rt", name: "rt", href: "#" },
    { abbr: "Rtc", name: "rtc", href: "#" },
    { abbr: "Rp", name: "rp", href: "#" },
    { abbr: "Bdi", name: "bdi", href: "#" },
    { abbr: "Bdo", name: "bdo", href: "#" },
    {
      abbr: "Ins",
      name: "ins",
      href: "/html/texto/etiqueta-html-ins-del/",
    },
    {
      abbr: "Del",
      name: "del",
      href: "/html/texto/etiqueta-html-ins-del/",
    },
  ],
  deprecated: [
    { abbr: "App", name: "applet", href: "/html/introduccion/etiquetas-html-obsoletas/" },
    { abbr: "Acr", name: "acronym", href: "/html/introduccion/etiquetas-html-obsoletas/" },
    { abbr: "Fr", name: "frame", href: "/html/introduccion/etiquetas-html-obsoletas/" },
    { abbr: "Fnt", name: "font", href: "/html/introduccion/etiquetas-html-obsoletas/" },
    { abbr: "Big", name: "big", href: "/html/introduccion/etiquetas-html-obsoletas/" },
    { abbr: "Blk", name: "blink", href: "/html/introduccion/etiquetas-html-obsoletas/" },
    { abbr: "Cen", name: "center", href: "/html/introduccion/etiquetas-html-obsoletas/" },
    { abbr: "Mrq", name: "marquee", href: "/html/introduccion/etiquetas-html-obsoletas/" },
  ]
};
